name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v3.2.2
      with:
        api-level: 35 
        build-tools: 36.0.0

    - name: Grant execute permission to Gradle wrapper
      run: chmod +x gradlew
    
    - name: Install dependencies
      run: ./gradlew build --stacktrace

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Generate unit test report
      run: ./gradlew testDebugUnitTest --info
      continue-on-error: true  

    - name: List available AVD devices
      run: $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager list device
      
    - name: Start Android Emulator
      uses: ReactiveCircus/android-emulator-runner@v2.33.0
      with:
        api-level: 36 
        target: google_apis
        arch: x86_64
        profile: pixel_7_pro
        avd-name: test-emulator
        emulator-options: "-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim"
        script: ./gradlew connectedDebugAndroidTest

    - name: Run UI tests (Espresso)
      run: ./gradlew connectedDebugAndroidTest
    
    - name: Generate UI test report
      run: ./gradlew connectedDebugAndroidTest --info
      continue-on-error: true
